name: Compress

# on:
#   pull_request:
#     paths:
#       - "src/**.png"
on:
  push:
    branches-ignore:
      - "**"

jobs:
  compress:
    name: Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Find symlinked paths to ignore
        id: find
        run: >-
          echo "::set-output name=ignore::$(find -L src -xtype l -type d | sed -e 's#$#/**#' | head -c -1 | tr '\n' ',')"
      - name: Check ignored paths
        run: echo ${{ steps.find.outputs.ignore }} | tr ',' '\n'
      - name: Compress Images
        uses: calibreapp/image-actions@9d037c06280028c110ff61c433ad4dc7d33c3c43 # 1.5.0
        with:
          ignorePaths: ${{ steps.find.outputs.ignore }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
